// flow-typed signature: 98a65464e85b10ced06b1fa836299c3d
// flow-typed version: <<STUB>>/react-native-navbar_v^2.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-navbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-navbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-navbar/lib' {
  declare module.exports: any;
}

declare module 'react-native-navbar/NavbarButton' {
  declare module.exports: any;
}

declare module 'react-native-navbar/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-navbar/index' {
  declare module.exports: $Exports<'react-native-navbar'>;
}
declare module 'react-native-navbar/index.js' {
  declare module.exports: $Exports<'react-native-navbar'>;
}
declare module 'react-native-navbar/lib.js' {
  declare module.exports: $Exports<'react-native-navbar/lib'>;
}
declare module 'react-native-navbar/NavbarButton.js' {
  declare module.exports: $Exports<'react-native-navbar/NavbarButton'>;
}
declare module 'react-native-navbar/styles.js' {
  declare module.exports: $Exports<'react-native-navbar/styles'>;
}
